### PR TITLE
replacing uvu with ava for testing

### PR DESCRIPTION
**Pull request by ShubhamSaini1585**
Hey, @gr2m @mikesurowiec @renovate-bot I've done the changes that you are wishing to be done in the files for testing. Please review

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks but there is more work to it than just a find & replace. The test files need to be updated to use ava’s assertions. Would you like to do that?

**Comment by ShubhamSaini1585** [comment]
yes @gr2m @mikesurowiec I am on it

**Comment by ShubhamSaini1585** [comment]
Hey, @gr2m @mikesurowiec I tried to do that but I couldn't find the solution for that. Also, the issue said to replace only. If you could merge the request t would be grateful for me.

**Comment by gr2m** [comment]
we cannot merge the pull request because it breaks the tests. That's what "Some checks were not successful" means.

Instead of using the `uvu/assert` module for assertions, we have to use ava's assertions, as documented here:
https://github.com/avajs/ava/blob/main/docs/03-assertions.md

**Comment by gr2m** [comment]
Please let me know if you'd still like to work on it, if not I'll just go ahead and do it myself, `ava` and its snapshot testing would come in very handy right now

**Comment by gr2m** [comment]
I'll do it myself

**Pull request closed without merging**
