### PR TITLE
fix: add closedAt

### PR DESCRIPTION
**Pull request by maxisam**
https://github.com/gr2m/github-project/issues/107

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
It's not that we missed it, we just have to find a balance between what is most commonly needed and the amount of data that is requested/transferred unnecessarily. But Happy to just add this one for now.

**Comment by gr2m** [comment]
Actually I think we should update test fixtures as part of this change, let me look into it, been a while

**Comment by gr2m** [comment]
Oh I get it now, sorry! The current code actually suggests that we load `closedAt` already, but we don't! Great Catch!

**Comment by Sam-Lin-MillersLab** [comment]
> Oh I get it now, sorry! The current code actually suggests that we load `closedAt` already, but we don't! Great Catch!

Thanks!

**Pull request merged**
